[book]
authors = ["Seb Blair"]
title = "Mobile Applications for Engineers and Technologists"
language = "en"
multilingual = false
src = "content"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/cccu-uk/ELEE1146-COMP1836_Labs/"
edit-url-template = "https://github.com/cccu-uk/ELEE1146-COMP1836/edit/master/{path}"

[output.html.print]
enable = false 

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
additional-js = ["./additional_scripts/on_download.js"]